#' Generate Clinical Biosurvey Query
#'
#' This function generates a SQL query for Clinical Biosurvey data based on the specified tier for BQ2 population(production, staging, or development).
#' It connects to Google's BigQuery, retrieves schema information, and builds a SQL query to fetch non-PII (Personally Identifiable Information) data.
#' 
#' @param tier Character string specifying the environment: 'prod' for production, 'stg' for staging, and 'dev' for development.
#' If none of these are matched, 'unknown-environment' is returned.
#'
#' @return A SQL query string for fetching Clinical Biosurvey data is written to an output file named 'clinicalbiosurvey.sql' in the corresponding tier directory.
#'
#' @details 
#' The function performs the following steps:
#' 1. Sets up the project ID based on the provided tier.
#' 2. Authenticates to BigQuery.
#' 3. Connects to the BigQuery database.
#' 4. Retrieves the data dictionary and schema information.
#' 5. Builds and writes the SQL query to the output file.
#'
#' @examples
#' generate_clinicalbiosurvey_query("prod")
#'
#' @author Jing Wu, Jake Peters, Rebecca Sansale
#'
generate_clinicalbiosurvey_query <- function(tier){

project <- switch(tier,
  prod = "nih-nci-dceg-connect-prod-6d04",
  stg  = "nih-nci-dceg-connect-stg-5519",
  dev  = "nih-nci-dceg-connect-dev",
  "unknown-environment"  # Default value if none of the cases match
)

library(bigrquery)
library(data.table)
library(tidyverse)
library(dplyr)
library(reshape)  
library(stringr)
library(plyr)
library(DBI)
library(quarto)
library(arsenal)
library(glue)

# Authenticate to BigQuery
bq_auth()

note <- "Note:
      This SQL query was generated by generate_bq2_queries.qmd. This code 
      lives in a GitHub repo (https://github.com/Analyticsphere/bq2). The 
      code was written by Jing Wu and edited by Jake Peters. The BQ2 tables 
      that are generated in this query are currated and maintained by Jake 
      Peters, Jing Wu and Rebecca Sansale. Other details will be documented here.."

#connect to BQ
con <- dbConnect(
  bigrquery::bigquery(),
  project = project,
  dataset = "FlatConnect",
  billing = project
)

#get the DD
#current text CID is used to match with schema values
source("custom_r_functions/get_dd.R")
dd <- get_dd(remove_pii = FALSE)
pii_cid <- dd[dd$PII == "Yes",]$conceptId.3
nopii_cid <- dd[dd$PII == "No",]$conceptId.3

#pull schema
# ToDo: 
table_name <- "clinicalBioSurvey_v1_JP"
sql <- glue("SELECT * 
            FROM `{project}.FlatConnect`.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS 
            WHERE table_name='{table_name}'")
query <- bq_project_query(project, query = sql)
schema <- bq_table_download(query, 
                             bigint="integer64", n_max = Inf, 
                             page_size = 500, quiet = TRUE)


#build the query
select <- paste(schema$column_name, collapse = ", \n\tb.")  
sql    <- glue(
      "
      /*
      Objective:
        Select all non-PII variables from {table}.
      
        For participants to be included:
         - Verification Status [821247024] MUST BE verified
         - Consent Withdrawn [747006172] MUST NOT be YES [353358909]
       
      {note}
      */
      
      SELECT 
        b.{select}
      FROM 
        `{project}.FlatConnect.{table_name}` b
      INNER JOIN `{project}.FlatConnect.participants_JP` p
        ON cast(b.Connect_ID as int64) = cast(p.Connect_ID as int64)
      WHERE 
        p.d_821247024 = '197316935'      -- is verified
        AND p.d_747006172 != '353358909' -- has not withdrawn consent")
   
   outputpath = glue("sql/{tier}/clinicalbiosurvey.sql")
   write.table(sql, file = outpath)
}