/*
Objective:
  
      Merge Module 2 v1/v2. If participants have completed both versions, only 
      the responses to v2 will be included.
      
      For participants to be included:
       - Verification Status [821247024] MUST BE verified
       - Consent Withdrawn [747006172] MUST NOT be YES [353358909]

Note:
      This SQL query was generated by generate_bq2_queries.qmd. This code 
      lives in a GitHub repo (enter link here). The code was written by Jing
      Wu and edited by Jake Peters. The BQ2 tables that are generated in this
      query are currated and maintained by Jake Peters, Jing Wu and Rebecca 
      Sansale. Other details will be documented here..
*/

WITH m2_dup AS
(SELECT 
   
  2 as version 
FROM 
  `nih-nci-dceg-connect-prod-6d04.FlatConnect.module2_v2_JP`
UNION ALL
SELECT
  , 
  1 as version 
FROM 
  `nih-nci-dceg-connect-prod-6d04.FlatConnect.module2_v1_JP`
-- Remove participants that completed both v1 & v2 from the table for v1.
WHERE 
  Connect_ID NOT IN ('8021087753',
	'3477605676',
	'5671051093',
	'8016812218',
	'1105606613',
	'4505692375',
	'1996085198',
	'3715901189',
	'1256197783',
	'5118827628',
	'2774891615',
	'9333929469',
	'1817817604',
	'8731246565',
	'2287983457',
	'6547756854',
	'1015390716',
	'8799687034',
	'4394283959',
	'6367118302',
	'8065823194',
	'8134860443',
	'8166039328',
	'9329247892',
	'8820522355')
)
SELECT 
  -- Select variables that are common to both versions
  dup.*,
  -- Select variables that are unique to v1
  ,
  -- Select variables that are unique to v2
  ,
  p.Connect_ID 
FROM
  m2_dup AS dup
LEFT JOIN `nih-nci-dceg-connect-prod-6d04.FlatConnect.module2_v1_JP` AS v1
  ON dup.Connect_ID = v1.Connect_ID
LEFT JOIN	`nih-nci-dceg-connect-prod-6d04.FlatConnect.module2_v2_JP` AS v2
  ON v2.Connect_ID = coalesce(dup.Connect_ID,v1.Connect_ID)
INNER JOIN `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` AS p
  ON coalesce(dup.Connect_ID, v1.Connect_ID, v2.Connect_ID) = p.Connect_ID
WHERE 
  p.d_821247024 = '197316935'      -- is verified 
  AND p.d_747006172 != '353358909' -- has not withdrawn consent 
